### ISSUE TITLE
Explore adding support for Deno

### ISSUE THREAD

**Issue by floodfx** [floodfx/liveviewjs#30]
A comment from HN says:
>I think deno may work out of the box with --compat flag but i haven't tried it.

**Comment by shah** [comment]
Would love to see out of the box Deno support -- hopefully without the `--compat` flag :-). Since LiveViewJS is a brand new project hopefully the core team can keep Node-specific calls isolated to allow it to work with Deno or Node through feature flags or other configuration settings (IoC for example). 

I'd love to contribute if there's interest in keeping the LVJS core Deno-ready (we don't use Node in our new projects anymore, but I love the concept of LiveViewJS).

**Comment by floodfx** [comment]
Great @shah!  How can I support you in this exploration?  I've done very basic Deno exploring in the past so not super familiar with what would need to happen to support (including without the `--compat` flag).  

- Do we need to use a different web socket and/or http server library?  
- How would we support parallel code bases?
- ??

You probably know way more about what needs to be done.  Would you mind documenting it in a bit more detail?

**Comment by floodfx** [comment]
fixed in #59
